### ISSUE TITLE
AD9959's suitability as a transceiver VFO

### ISSUE THREAD

**Issue by prt459** [cjheath/AD9959#1]
Hi Clifford, 
I'd like to move on from si5351 VFOs in transceiver projects, and the AD9959 looks like an obvious candidate, now that the 5V boards are on eBay and Ali at good prices.  The issue is update speed.  Do you expect setFrequency() would adjust one of the channel's frequencies sufficiently fast to emulate an analogue VFO?  You want to be able to spin an optical encoder and have the DDS keep up.
regards Paul VK3HN. 

PS. We did CS together if I remember correctly!

**Comment by cjheath** [comment]
You can update the frequency *very* fast, multiple times per microsecond if you can send SPI fast enough. The way the DDS works, there is no phase discontinuity when you apply a new frequency word - because the accumulator is unaffected. It just starts to step at the new delta. However, you should probably compute the delta values for the two extremes of your modulation range, interpolate based on your audio, and then use _setDelta_ - it doesn't require the 64-bit division (which frequencyDelta computes using reciprocal multiplication). Let me know how you go, because I have only tested this library "in vitro" so far - the project using it was suspended for a while.

Nice to make contact again after all these years. Unfortunately I have only a very limited memory of my class-mates in CS, but if you remember me, I believe you. Did we do a project together? I still have some of my source-code printouts!

**Comment by prt459** [comment]
Hi Clifford, thanks for your quick response.  I wouldn't be modulating the channel, just taking the sine wave  via a buffer/gain stage to a mixer.  Sounds like it would be plenty fast enough.  I just checked the Analog devices data sheet, and the DAC is 10 bit.  The AD9951 (14 bit DAC) will give a purer sine approximation and lower phase noise in a receiver application.  And I don't need 4 channels.  I might look at that device.  

We met at Moody's EA Conference at Luna Park a few years back. Maybe at some Melbourne software events before that. We didn't do a project together from memory.  

Good luck with your projects!

**Comment by cjheath** [comment]
Feel free to steal my reciprocal division code, with attribution. I'm rather proud of it, and it took multiple days to get confident it was working correctly.

I sent a LinkedIn request, let me know if it was mis-targeted and you didn't get it.

**Comment by cjheath** [comment]
Hi again Paul. I haven't received work that there's any remaining issue here, so I'm closing this. Feel free to let know if you had success with your project.
