### ISSUE TITLE
How to set the profile pins using the software -urgent request

### ISSUE THREAD

**Issue by Hanros94** [cjheath/AD9959#7]
Hi 

I have been able to get your code working but I was wondering how to set the profile pins without making use of an external signal to the profile pins in the U2 header. As it is possible in the proprietary software I assume it should be possible to set these pins in the software as well. Could you please advise me.

**Comment by cjheath** [comment]
My software does not have a U2 header. It is software. What hardware do you want help with?

It is necessary to connect additional control pins (including the profile pins) to drive the AD9959. This software does not do that, because every project will do it differently. They're just GPIO pins - if you're using Arduino, look for digitalWrite()
